# Generated by Django 4.2.11 on 2026-08-04 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0020_censo_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='reservado_por_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_reservados', to=settings.AUTH_USER_MODEL),
        ),
    ]
